services:
  app:
    container_name: "laravel-12-mantine-app"
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    build: 
      context: .
      dockerfile: ./docker/docker.prod.Dockerfile
    command: > 
      bash -c "
      npm install;
      composer install;
      npm run build;
      php-fpm -R;"
    restart: "no"
  nginx:
    container_name: "camera-trailer-alerts-nginx"
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
  db:
    ports:
      - "3306:3306"
    image: mysql:8
    container_name: "laravel-12-mantine-db"
    restart: "no"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
